apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv-lab6
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/namenode"