apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
  - name: "hdfs-port-for-clients"
    port: 9870
    targetPort: 9870
  - name: "ipc-port"
    port: 9000
    targetPort: 9000
  clusterIP: None
