#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kmeans-lab6
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  image: "ddulaev/lab6:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/main.py"
  sparkVersion: "3.4.1"
  restartPolicy:
    type: Always
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.4.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "16g"
    labels:
      version: 3.4.1
